var annotated_dup =
[
    [ "athena", null, [
      [ "io", null, [
        [ "ALTTPFileReader", "classathena_1_1io_1_1_a_l_t_t_p_file_reader.html", "classathena_1_1io_1_1_a_l_t_t_p_file_reader" ],
        [ "ALTTPFileWriter", "classathena_1_1io_1_1_a_l_t_t_p_file_writer.html", "classathena_1_1io_1_1_a_l_t_t_p_file_writer" ],
        [ "Buffer", "structathena_1_1io_1_1_buffer.html", "structathena_1_1io_1_1_buffer" ],
        [ "BufferYaml", "structathena_1_1io_1_1_buffer_yaml.html", "structathena_1_1io_1_1_buffer_yaml" ],
        [ "DNA", "structathena_1_1io_1_1_d_n_a.html", "structathena_1_1io_1_1_d_n_a" ],
        [ "DNAYaml", "structathena_1_1io_1_1_d_n_a_yaml.html", "structathena_1_1io_1_1_d_n_a_yaml" ],
        [ "FileReader", "classathena_1_1io_1_1_file_reader.html", "classathena_1_1io_1_1_file_reader" ],
        [ "FileWriter", "classathena_1_1io_1_1_file_writer.html", "classathena_1_1io_1_1_file_writer" ],
        [ "IStream", "classathena_1_1io_1_1_i_stream.html", "classathena_1_1io_1_1_i_stream" ],
        [ "IStreamReader", "classathena_1_1io_1_1_i_stream_reader.html", "classathena_1_1io_1_1_i_stream_reader" ],
        [ "IStreamWriter", "classathena_1_1io_1_1_i_stream_writer.html", "classathena_1_1io_1_1_i_stream_writer" ],
        [ "MCFileReader", "classathena_1_1io_1_1_m_c_file_reader.html", "classathena_1_1io_1_1_m_c_file_reader" ],
        [ "MCFileWriter", "classathena_1_1io_1_1_m_c_file_writer.html", "classathena_1_1io_1_1_m_c_file_writer" ],
        [ "MemoryCopyReader", "classathena_1_1io_1_1_memory_copy_reader.html", "classathena_1_1io_1_1_memory_copy_reader" ],
        [ "MemoryCopyWriter", "classathena_1_1io_1_1_memory_copy_writer.html", "classathena_1_1io_1_1_memory_copy_writer" ],
        [ "MemoryReader", "classathena_1_1io_1_1_memory_reader.html", "classathena_1_1io_1_1_memory_reader" ],
        [ "MemoryWriter", "classathena_1_1io_1_1_memory_writer.html", "classathena_1_1io_1_1_memory_writer" ],
        [ "SkywardSwordFileReader", "classathena_1_1io_1_1_skyward_sword_file_reader.html", "classathena_1_1io_1_1_skyward_sword_file_reader" ],
        [ "SkywardSwordFileWriter", "classathena_1_1io_1_1_skyward_sword_file_writer.html", "classathena_1_1io_1_1_skyward_sword_file_writer" ],
        [ "SpriteFileReader", "classathena_1_1io_1_1_sprite_file_reader.html", "classathena_1_1io_1_1_sprite_file_reader" ],
        [ "SpriteFileWriter", "classathena_1_1io_1_1_sprite_file_writer.html", "classathena_1_1io_1_1_sprite_file_writer" ],
        [ "String", "structathena_1_1io_1_1_string.html", "structathena_1_1io_1_1_string" ],
        [ "StringYaml", "structathena_1_1io_1_1_string_yaml.html", "structathena_1_1io_1_1_string_yaml" ],
        [ "WiiSaveReader", "classathena_1_1io_1_1_wii_save_reader.html", "classathena_1_1io_1_1_wii_save_reader" ],
        [ "WiiSaveWriter", "classathena_1_1io_1_1_wii_save_writer.html", "classathena_1_1io_1_1_wii_save_writer" ],
        [ "WString", "structathena_1_1io_1_1_w_string.html", "structathena_1_1io_1_1_w_string" ],
        [ "WStringAsString", "structathena_1_1io_1_1_w_string_as_string.html", "structathena_1_1io_1_1_w_string_as_string" ],
        [ "WStringAsStringYaml", "structathena_1_1io_1_1_w_string_as_string_yaml.html", "structathena_1_1io_1_1_w_string_as_string_yaml" ],
        [ "WStringYaml", "structathena_1_1io_1_1_w_string_yaml.html", "structathena_1_1io_1_1_w_string_yaml" ],
        [ "YAMLDocReader", "classathena_1_1io_1_1_y_a_m_l_doc_reader.html", "classathena_1_1io_1_1_y_a_m_l_doc_reader" ],
        [ "YAMLDocWriter", "classathena_1_1io_1_1_y_a_m_l_doc_writer.html", "classathena_1_1io_1_1_y_a_m_l_doc_writer" ],
        [ "YAMLNode", "structathena_1_1io_1_1_y_a_m_l_node.html", "structathena_1_1io_1_1_y_a_m_l_node" ],
        [ "YAMLStdStringReaderState", "structathena_1_1io_1_1_y_a_m_l_std_string_reader_state.html", "structathena_1_1io_1_1_y_a_m_l_std_string_reader_state" ],
        [ "ZQuestFileReader", "classathena_1_1io_1_1_z_quest_file_reader.html", "classathena_1_1io_1_1_z_quest_file_reader" ],
        [ "ZQuestFileWriter", "classathena_1_1io_1_1_z_quest_file_writer.html", "classathena_1_1io_1_1_z_quest_file_writer" ]
      ] ],
      [ "Sakura", null, [
        [ "Sprite", "classathena_1_1_sakura_1_1_sprite.html", "classathena_1_1_sakura_1_1_sprite" ],
        [ "SpriteFile", "classathena_1_1_sakura_1_1_sprite_file.html", "classathena_1_1_sakura_1_1_sprite_file" ],
        [ "SpriteFrame", "classathena_1_1_sakura_1_1_sprite_frame.html", "classathena_1_1_sakura_1_1_sprite_frame" ],
        [ "SpritePart", "classathena_1_1_sakura_1_1_sprite_part.html", "classathena_1_1_sakura_1_1_sprite_part" ],
        [ "STexture", "structathena_1_1_sakura_1_1_s_texture.html", "structathena_1_1_sakura_1_1_s_texture" ],
        [ "Vector2D", "classathena_1_1_sakura_1_1_vector2_d.html", "classathena_1_1_sakura_1_1_vector2_d" ]
      ] ],
      [ "ALTTPAbilities", "structathena_1_1_a_l_t_t_p_abilities.html", "structathena_1_1_a_l_t_t_p_abilities" ],
      [ "ALTTPCrystals", "structathena_1_1_a_l_t_t_p_crystals.html", "structathena_1_1_a_l_t_t_p_crystals" ],
      [ "ALTTPDungeonItemFlags", "structathena_1_1_a_l_t_t_p_dungeon_item_flags.html", "structathena_1_1_a_l_t_t_p_dungeon_item_flags" ],
      [ "ALTTPFile", "classathena_1_1_a_l_t_t_p_file.html", "classathena_1_1_a_l_t_t_p_file" ],
      [ "ALTTPInventory", "structathena_1_1_a_l_t_t_p_inventory.html", "structathena_1_1_a_l_t_t_p_inventory" ],
      [ "ALTTPLightDarkWorldIndicator", "structathena_1_1_a_l_t_t_p_light_dark_world_indicator.html", "structathena_1_1_a_l_t_t_p_light_dark_world_indicator" ],
      [ "ALTTPMagicUsage", "structathena_1_1_a_l_t_t_p_magic_usage.html", "structathena_1_1_a_l_t_t_p_magic_usage" ],
      [ "ALTTPOverworldEvent", "structathena_1_1_a_l_t_t_p_overworld_event.html", "structathena_1_1_a_l_t_t_p_overworld_event" ],
      [ "ALTTPPendants", "structathena_1_1_a_l_t_t_p_pendants.html", "structathena_1_1_a_l_t_t_p_pendants" ],
      [ "ALTTPProgressFlags1", "structathena_1_1_a_l_t_t_p_progress_flags1.html", "structathena_1_1_a_l_t_t_p_progress_flags1" ],
      [ "ALTTPProgressFlags2", "structathena_1_1_a_l_t_t_p_progress_flags2.html", "structathena_1_1_a_l_t_t_p_progress_flags2" ],
      [ "ALTTPQuest", "classathena_1_1_a_l_t_t_p_quest.html", "classathena_1_1_a_l_t_t_p_quest" ],
      [ "ALTTPRoomFlags", "structathena_1_1_a_l_t_t_p_room_flags.html", "structathena_1_1_a_l_t_t_p_room_flags" ],
      [ "Dir", "classathena_1_1_dir.html", "classathena_1_1_dir" ],
      [ "FileInfo", "classathena_1_1_file_info.html", "classathena_1_1_file_info" ],
      [ "MCFile", "classathena_1_1_m_c_file.html", "classathena_1_1_m_c_file" ],
      [ "MCSlot", "classathena_1_1_m_c_slot.html", "classathena_1_1_m_c_slot" ],
      [ "SkywardSwordFile", "classathena_1_1_skyward_sword_file.html", "classathena_1_1_skyward_sword_file" ],
      [ "SkywardSwordQuest", "classathena_1_1_skyward_sword_quest.html", "classathena_1_1_skyward_sword_quest" ],
      [ "WiiBanner", "classathena_1_1_wii_banner.html", "classathena_1_1_wii_banner" ],
      [ "WiiFile", "classathena_1_1_wii_file.html", "classathena_1_1_wii_file" ],
      [ "WiiImage", "classathena_1_1_wii_image.html", "classathena_1_1_wii_image" ],
      [ "WiiSave", "classathena_1_1_wii_save.html", "classathena_1_1_wii_save" ],
      [ "ZQuestFile", "classathena_1_1_z_quest_file.html", "classathena_1_1_z_quest_file" ]
    ] ],
    [ "alignas", "unionalignas.html", "unionalignas" ]
];